// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZZW3pt1JeQ9wQewN5Sh--mUpfWu5V8LY',
    appId: '1:565950325269:web:8fee937352f1fafe28241c',
    messagingSenderId: '565950325269',
    projectId: 'autoclub-ai',
    authDomain: 'autoclub-ai.firebaseapp.com',
    storageBucket: 'autoclub-ai.firebasestorage.app',
    measurementId: 'G-SP3D7VW6TQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKhxZ841CtanWIQBgPYh5snfpxXxmKpV8',
    appId: '1:565950325269:android:6d0969fa4e8c896128241c',
    messagingSenderId: '565950325269',
    projectId: 'autoclub-ai',
    storageBucket: 'autoclub-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARkhjZXEKCl58XMMjffxd2qHNwx3CHhG0',
    appId: '1:565950325269:ios:ab37e4313fc3494528241c',
    messagingSenderId: '565950325269',
    projectId: 'autoclub-ai',
    storageBucket: 'autoclub-ai.firebasestorage.app',
    iosBundleId: 'com.example.autoClubAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARkhjZXEKCl58XMMjffxd2qHNwx3CHhG0',
    appId: '1:565950325269:ios:ab37e4313fc3494528241c',
    messagingSenderId: '565950325269',
    projectId: 'autoclub-ai',
    storageBucket: 'autoclub-ai.firebasestorage.app',
    iosBundleId: 'com.example.autoClubAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZZW3pt1JeQ9wQewN5Sh--mUpfWu5V8LY',
    appId: '1:565950325269:web:c1f18b4de7d0c07a28241c',
    messagingSenderId: '565950325269',
    projectId: 'autoclub-ai',
    authDomain: 'autoclub-ai.firebaseapp.com',
    storageBucket: 'autoclub-ai.firebasestorage.app',
    measurementId: 'G-DR90MXJGNC',
  );
}
